### PR TITLE
Feat/ollama setup integration

### PR DESCRIPTION
**Pull request by hdprajwal**
This PR sets up the basic webui exrtension

### CODE REVIEW

**Comment by adithya1012** [comment]
Working in my local.

**Review by adithya1012 — APPROVED** [review]

**Review by Sinduja98 — APPROVED** [review]
It is working fine on my local.

**Comment by jahnavib26** [comment]
Works for me!

**Review by jahnavib26 — APPROVED** [review]

**Review by nidhitalastha — APPROVED** [review]
Looks good to me!

**Pull request merged**
