### PR TITLE
Update extension from JS to TS

### PR DESCRIPTION
**Pull request by hdprajwal**
This PR updates the project to use Typescript and adds basic boilerplate webview-ui.

### CODE REVIEW

**Comment by Sinduja98** [comment]
This looks good to me, it would be good to add an asset folder.

**Comment by adithya1012** [comment]
image

Not working in my local.

**Comment by hdprajwal** [comment]
> Not working in my local.

Can you try fresh installing node packages, It probably is the issue with old node modules

**Comment by jahnavib26** [comment]
This worked perfectly for me, but I had to update the VS Code version in package.json to get the code running.

**Comment by adithya1012** [comment]
Works in my local after following the steps below:

1. update VS code version in package.json.
2. install esbuild problem matcher extension.
3. running npm i before running file.

**Review by Sinduja98 — APPROVED** [review]
Now, it looks good and it's working on my local.

**Review by adithya1012 — APPROVED** [review]

**Review by jahnavib26 — APPROVED** [review]

**Review by nidhitalastha — APPROVED** [review]
Looks good to me!

**Pull request merged**
