### PR TITLE
Integrate extension logic with Chat UI component

### PR DESCRIPTION
**Pull request by nidhitalastha**
This pull request includes the following changes and improvement.

### Core Functionality Enhancements:

* Added flags in `src/core/index.ts` to track the state of tool usage and send events to the webview, enhancing the functionality of the `DevAssist` class.
* Added events to manage state between extension and webview UI. 
* Added extension context in webview UI to maintain centralized extension state.
* Added logic to handle user input and assistant messages in extensionContext.
* Adds UI fixes such as scroll area for ChatLayout, loader component for request in process, chatComponent to handle assistant messages.

### CODE REVIEW

**Review by Sinduja98 — APPROVED** [review]
When user prompt is given, it is automatically executing the code in the terminal. It should be executed only when the user asks to execute the code.

**Comment by adithya1012** [comment]
> When user prompt is given, it is automatically executing the code in the terminal. It should be executed only when the user asks to execute the code.


Even i see that program is executing when we ask to create a file. I got the issue. i have updated system.ts file and it is working for me. I will update this in the same PR.

**Review by hdprajwal — APPROVED** [review]
Looks good to me!

**Review by adithya1012 — APPROVED** [review]
updated system.ts and working in my local.

**Comment by jahnavib26** [comment]
Working in my system with the system.ts

**Review by jahnavib26 — APPROVED** [review]

**Pull request merged**
