### PR TITLE
Retaining the chat history.

### PR DESCRIPTION
**Pull request by adithya1012**
This PR introduces the following key updates:  

1. **`ask_followup_Question` Tool**  
   - Added a new tool, `ask_followup_Question`, enabling the LLM to ask follow-up questions when the user's prompt is unclear.  

2. **Chat Retention Feature**  
   - Implemented a feature to retain the chat context.  
   - Each user-assistant conversation will now be passed to the LLM for context in subsequent requests.  

### Testing  
- Tested successfully with Gemini.  

### Known Issues  
- Occasionally, XML tags are retained in the content while parsing messages.  
  - **Possible Solution**: Further tuning of `system.ts` and additional checks during data parsing may be required to resolve this issue.

### CODE REVIEW

**Review by hdprajwal — APPROVED** [review]
Looks good to me!

**Review by nidhitalastha — APPROVED** [review]
Looks good to me!

**Review by Sinduja98 — APPROVED** [review]
Looks good.

**Comment by jahnavib26** [comment]
Works on my system!

**Review by jahnavib26 — APPROVED** [review]

**Pull request merged**
