### PR TITLE
Add API Configuration UI for LLMs

### PR DESCRIPTION
**Pull request by Sinduja98**
This PR introduces a new feature that enables users to configure API settings for different LLM providers, including Google Gemini and OpenAI, directly from the user interface. The feature includes a settings icon on the UI, allowing users to provide API keys and select specific models at any point in the process.

**Features Added:**

_UI Enhancements:_
- Added a settings icon to the interface.
- Created a dedicated UI for API configuration with dropdowns, text fields, and relevant labels.

_API Configuration Options:_
- Allows users to select an API provider (Google Gemini or OpenAI).
- Users can input and securely store API keys locally:
       - Google Gemini API Key
       -  OpenAI API Key
- Users can choose models from dynamically updated lists specific to the selected provider.

### CODE REVIEW

**Review by nidhitalastha — APPROVED** [review]
LGTM!

**Review by adithya1012 — APPROVED** [review]
Look good !

**Review by hdprajwal — APPROVED** [review]
LGTM!

**Comment by jahnavib26** [comment]
Looks good!

**Review by jahnavib26 — APPROVED** [review]

**Pull request merged**
